export const EMBED_TEXT_ATTACHMENTS_KEY = "EMBED_TEXT_ATTACHMENTS";
export const COPY_MEDIA_TO_CLIPBOARD_KEY = "COPY_MEDIA_TO_CLIPBOARD";
export const ADD_AI_PROMPT_KEY = "ADD_AI_PROMPT";

export const EMBED_TEXT_ATTACHMENTS_DEFAULT = true;
export const COPY_MEDIA_TO_CLIPBOARD_DEFAULT = false;
export const ADD_AI_PROMPT_DEFAULT = true;

export const MAX_MEDIA_CLIPBOARD_ITEMS = 20;
export const MEDIA_CLIPBOARD_DELAY_MS = 100;
