/** @deprecated migrated to SPD_EMBED_TEXT_ATTACHMENTS */
export const SPD_COPY_FORMATTED_KEY = "SPD_COPY_FORMATTED";

export const SPD_EMBED_TEXT_ATTACHMENTS_KEY = "SPD_EMBED_TEXT_ATTACHMENTS";
export const SPD_COPY_MEDIA_TO_CLIPBOARD_KEY = "SPD_COPY_MEDIA_TO_CLIPBOARD";
export const SPD_ADD_AI_PROMPT_KEY = "SPD_ADD_AI_PROMPT";

export const SPD_EMBED_TEXT_ATTACHMENTS_DEFAULT = true;
export const SPD_COPY_MEDIA_TO_CLIPBOARD_DEFAULT = true;
export const SPD_ADD_AI_PROMPT_DEFAULT = false;

export const MAX_MEDIA_CLIPBOARD_ITEMS = 20;
export const MEDIA_CLIPBOARD_DELAY_MS = 100;
